
# tasks file for roles/docker
---
- name: Install Docker
  ansible.builtin.apt:
    name: docker.io
    state: present
    update_cache: true

- name: Start Docker
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Add deploy user to Docker group
  ansible.builtin.user:
    name: "{{ deploy_user }}"
    groups: docker
    append: true
